services:
  # Open WebUI service configuration
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "3000:8080"  # Maps host port 3000 to container port 8080
    environment:
      - WEBUI_AUTH_ENABLED=false
      - WEBUI_URL=http://localhost:3000
    volumes:
      - open-webui-data:/app/backend/data

volumes:
  open-webui-data: