spring:
  application:
    name: @project.artifactId@
  ai:
    ollama:
      base-url: http://192.168.68.121:11434
      chat:
        options:
          model: "llama3.1:8b"
    mcp:
      client:
        enabled: true
        name: spring-ai-mcp-client
        version: 1.0.0
        request-timeout: 60s
        type: sync
        sse:
          connections:
            server1:
              url: http://localhost:8080
              sse-endpoint: /sse
        root-change-notification: true
        toolcallback:
          enabled: true
logging:
  level:
    web: debug
    org.springframework.ai.mcp: TRACE
    io.modelcontextprotocol:
      client: WARN
      spec: WARN
server:
  port: 8088
gg:
  jte:
    development-mode: true